version: "3"
services:
  ytdl-sub:
    container_name: ytdl-sub
    image: ghcr.io/jmbannon/ytdl-sub:latest
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri  # CPU passthrough. SEE https://ytdl-sub.readthedocs.io/en/latest/guides/install/docker.html for GPU
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
      - DOCKER_MODS=linuxserver/mods:universal-cron
    volumes:
      - ./config:/config #Do not change
      - path/to/tv_shows:/tv_shows
      - path/to/movies:/movies
      - path/to/music_videos:/music_videos
      - path/to/music:/music

  tiny-sub-webgui:
    container_name: tiny-sub-webgui
    image: tinyfilemanager/tinyfilemanager:master
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
    volumes:
      - ./config:/var/www/html/data #Do not change
      - ./tfm/index.php:/var/www/html/index.php:ro # Prevent updates from overwriting the custom page
    ports:
      - 3132:80
networks: {}
